import type { CountryOption } from "./dropdownSelectCountry";

// Европа (включая широкое определение: ЕЭЗ, Кавказ, Микрогос-ва, TR) + Казахстан.
export const countriesEurope: CountryOption[] = [
  { code: "AL", title: "Albania" },
  { code: "AD", title: "Andorra" },
  { code: "AM", title: "Armenia" },
  { code: "AT", title: "Austria" },
  { code: "AZ", title: "Azerbaijan" },
  { code: "BY", title: "Belarus" },
  { code: "BE", title: "Belgium" },
  { code: "BA", title: "Bosnia and Herzegovina" },
  { code: "BG", title: "Bulgaria" },
  { code: "HR", title: "Croatia" },
  { code: "CY", title: "Cyprus" },
  { code: "CZ", title: "Czechia" },
  { code: "DK", title: "Denmark" },
  { code: "EE", title: "Estonia" },
  { code: "FI", title: "Finland" },
  { code: "FR", title: "France" },
  { code: "GE", title: "Georgia" },
  { code: "DE", title: "Germany" },
  { code: "GR", title: "Greece" },
  { code: "HU", title: "Hungary" },
  { code: "IS", title: "Iceland" },
  { code: "IE", title: "Ireland" },
  { code: "IT", title: "Italy" },
  { code: "KZ", title: "Kazakhstan" },
  { code: "LV", title: "Latvia" },
  { code: "LI", title: "Liechtenstein" },
  { code: "LT", title: "Lithuania" },
  { code: "LU", title: "Luxembourg" },
  { code: "MT", title: "Malta" },
  { code: "MD", title: "Moldova" },
  { code: "MC", title: "Monaco" },
  { code: "ME", title: "Montenegro" },
  { code: "NL", title: "Netherlands" },
  { code: "MK", title: "North Macedonia" },
  { code: "NO", title: "Norway" },
  { code: "PL", title: "Poland" },
  { code: "PT", title: "Portugal" },
  { code: "RO", title: "Romania" },
  { code: "RU", title: "Russia" },
  { code: "SM", title: "San Marino" },
  { code: "RS", title: "Serbia" },
  { code: "SK", title: "Slovakia" },
  { code: "SI", title: "Slovenia" },
  { code: "ES", title: "Spain" },
  { code: "SE", title: "Sweden" },
  { code: "CH", title: "Switzerland" },
  { code: "TR", title: "Türkiye" },
  { code: "UA", title: "Ukraine" },
  { code: "GB", title: "United Kingdom" },
  { code: "VA", title: "Vatican City" },
];
